'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');
const {ensureStorage}=require('../../src/core/storage');const {CaseStore}=require('../../src/services/cases/case-store');const {ActiveCaseLock}=require('../../src/services/cases/active-case-lock');const {InboxScanner}=require('../../src/services/cases/inbox-scanner');const {assertTransition}=require('../../src/services/cases/case-state-machine');const {CaseWorkflowService}=require('../../src/services/cases/case-workflow-service');const {reconcileFinalBill}=require('../../src/services/final-bill');
function setup(options={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'vnext-cases-'));ensureStorage(root);let id=0;const clock=options.clock||(()=>new Date('2026-09-26T10:00:00Z'));const store=new CaseStore(root,{clock,idFactory:()=>`id-${++id}`,copy:options.copy});return{root,store,clock};}
function source(hash='hash-a'){return{file_name:`${hash}.pdf`,sha256:hash};}function makePdf(dir,name,body='%PDF- synthetic'){const f=path.join(dir,name);fs.writeFileSync(f,body);return f;}function sha(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');}
function advance(store,id,to){return store.transition(id,to,`to ${to}`);}function portalReady(store,id){advance(store,id,'INGESTING');advance(store,id,'READY_FOR_PLAN');advance(store,id,'PLAN_READY');advance(store,id,'READY_FOR_PORTAL');}

test('P8-01 new initial PDF hash creates a durable case',()=>{const{store}=setup();const r=store.create(source());assert.equal(r.outcome,'NEW_SOURCE');assert.equal(r.case.workflow_status,'NEW');assert.ok(fs.existsSync(store.manifestFile(r.case.case_id)));});
test('P8-02 same initial hash returns exact duplicate and no second case',()=>{const{store}=setup();const a=store.create(source());const b=store.create(source());assert.equal(b.outcome,'EXACT_DUPLICATE');assert.equal(a.case.case_id,b.case.case_id);assert.equal(store.list().length,1);});
test('P8-03 different hash creates a distinct case',()=>{const{store}=setup();assert.notEqual(store.create(source('a')).case.case_id,store.create(source('b')).case.case_id);});
test('P8-04 file becomes stable only after unchanged deterministic observations',()=>{const{root}=setup();let now=Date.now()+5000;const scanner=new InboxScanner(root,{clock:()=>now,minAgeMs:0});const f=makePdf(scanner.initial,'a.pdf');assert.equal(scanner.scan()[0].status,'WAITING_FOR_STABLE_FILE');assert.equal(scanner.scan()[0].status,'STABLE');assert.equal(scanner.scan()[0].sha256,sha(f));});
test('P8-05 changed/partially copied file returns to waiting state',()=>{const{root}=setup();const scanner=new InboxScanner(root,{minAgeMs:0});const f=makePdf(scanner.initial,'a.pdf');scanner.scan();fs.appendFileSync(f,'more');assert.equal(scanner.scan()[0].status,'WAITING_FOR_STABLE_FILE');});
test('P8-06 temporary and non-PDF files are ignored',()=>{const{root}=setup();const s=new InboxScanner(root,{minAgeMs:0});makePdf(s.initial,'.hidden.pdf');makePdf(s.initial,'a.part');makePdf(s.initial,'note.txt');assert.deepEqual(s.scan(),[]);});
test('P8-07 case manifest survives application restart simulation',()=>{const{root,store}=setup();const c=store.create(source()).case;advance(store,c.case_id,'INGESTING');const restarted=new CaseStore(root);assert.equal(restarted.load(c.case_id).workflow_status,'INGESTING');});
test('P8-08 active lock prevents simultaneous portal execution',()=>{const{root}=setup();const one=new ActiveCaseLock(root,{pid:process.pid});one.acquire('case-a');const two=new ActiveCaseLock(root,{pid:process.pid});assert.throws(()=>two.acquire('case-b'),/ACTIVE_CASE_LOCKED:case-a/);one.release();});
test('P8-09 stale active lock is recoverable',()=>{const{root}=setup();const lock=new ActiveCaseLock(root,{clock:()=>new Date('2026-09-26T12:00:00Z'),maxAgeMs:1000,pid:12345});fs.writeFileSync(lock.file,JSON.stringify({case_id:'old',pid:999999,token:'x',acquired_at:'2026-09-26T10:00:00Z',heartbeat_at:'2026-09-26T10:00:00Z'}));assert.equal(lock.recoverStale().case_id,'old');assert.equal(fs.existsSync(lock.file),false);});
test('P8-10 plan registry hash and revision persist in manifest',()=>{const{store}=setup();const c=store.create(source()).case;store.patch(c.case_id,{enhancement_plan_reference:{registry_hash:'abc',registry_revision:7,path:'plan.json'}});const m=store.load(c.case_id);assert.equal(m.enhancement_plan_reference.registry_hash,'abc');assert.equal(m.enhancement_plan_reference.registry_revision,7);});
test('P8-11 changed custom registry still raises PLAN_STALE at existing adapter boundary',()=>{const {adaptEnhancementPlan}=require('../../src/adapters/legacy-portal/plan-adapter');const plan={plan_version:'1',entries:[],custom_registry:{relevant_record_hashes:{LC001:null}}};assert.throws(()=>adaptEnhancementPlan(plan,{registrySnapshot:{record_hashes:{LC001:'changed'}}}),/PLAN_STALE/);});
test('P8-12 final PDF exact identifiers associate with intended case',()=>{const initial={billing:{bill_number:'B1'},patient:{uhid:'U1',ip_number:'I1'}};const final=structuredClone(initial);assert.equal(reconcileFinalBill(initial,final).status,'MATCHED');});
test('P8-13 conflicting final identifier produces MATCH_REQUIRED',()=>{const initial={billing:{bill_number:'B1'},patient:{uhid:'U1'}};const final={billing:{bill_number:'B2'},patient:{uhid:'U1'}};assert.equal(reconcileFinalBill(initial,final).status,'MATCH_REQUIRED');});
test('P8-14 unmatched final bill never selects a recent case',()=>{const initial={billing:{},patient:{}};const final={billing:{},patient:{}};assert.equal(reconcileFinalBill(initial,final).decision,'INSUFFICIENT_IDENTIFIERS');});
test('P8-15 completed case cannot be silently overwritten',()=>{const{store}=setup();const c=store.create(source()).case;portalReady(store,c.case_id);advance(store,c.case_id,'PORTAL_EXECUTING');advance(store,c.case_id,'PORTAL_EXECUTED');advance(store,c.case_id,'VERIFICATION_REQUIRED');advance(store,c.case_id,'DISCHARGE_REQUIRED');advance(store,c.case_id,'FINAL_BILL_REQUIRED');advance(store,c.case_id,'FINAL_BILL_LOADED');advance(store,c.case_id,'READY_TO_SAVE');advance(store,c.case_id,'COMPLETED');assert.throws(()=>store.patch(c.case_id,{bill_number:'changed'}),/immutable/);});
test('P8-16 explicit reprocessing creates linked new case version',()=>{const{store}=setup();const c=store.create(source()).case;const next=store.reprocess(c.case_id,source());assert.equal(next.outcome,'REPROCESSED');assert.equal(next.case.parent_case_id,c.case_id);assert.equal(next.case.version,2);});
test('P8-17 interrupted portal execution recovers without auto-resume',()=>{const{root,store}=setup();const c=store.create(source()).case;portalReady(store,c.case_id);advance(store,c.case_id,'PORTAL_EXECUTING');const lock=new ActiveCaseLock(root,{pid:process.pid});const svc=new CaseWorkflowService({store,lock,rateRepository:{},registrySnapshot:()=>({}),storageRoot:root});assert.deepEqual(svc.interruptPortalCases(),[c.case_id]);assert.equal(store.load(c.case_id).workflow_status,'RECOVERY_REQUIRED');});
test('P8-18 discharge confirmation records acknowledgement only and performs no portal action',()=>{const{root,store}=setup();const c=store.create(source()).case;portalReady(store,c.case_id);advance(store,c.case_id,'PORTAL_EXECUTING');advance(store,c.case_id,'PORTAL_EXECUTED');advance(store,c.case_id,'VERIFICATION_REQUIRED');advance(store,c.case_id,'DISCHARGE_REQUIRED');const svc=new CaseWorkflowService({store,lock:new ActiveCaseLock(root),rateRepository:{},registrySnapshot:()=>({}),storageRoot:root});svc.confirmDischarge(c.case_id,'OP-1');assert.equal(store.load(c.case_id).workflow_status,'FINAL_BILL_REQUIRED');assert.ok(store.auditRecords(c.case_id).some(e=>e.event==='DISCHARGE_CONFIRMED'&&/no portal action/i.test(e.reason)));});
test('P8-19 invalid state transition is rejected',()=>{assert.throws(()=>assertTransition('NEW','COMPLETED'),/Invalid case transition/);});
test('P8-20 transition audit contains previous and new state',()=>{const{store}=setup();const c=store.create(source()).case;advance(store,c.case_id,'INGESTING');const event=store.auditRecords(c.case_id).at(-1);assert.equal(event.previous_state,'NEW');assert.equal(event.new_state,'INGESTING');});
test('P8-21 archive failure is explicit and source is not deleted',()=>{const{store}=setup({copy:()=>{throw new Error('disk full');}});const dir=fs.mkdtempSync(path.join(os.tmpdir(),'src-'));const f=makePdf(dir,'a.pdf');const c=store.create(source()).case;const result=store.archive(c.case_id,f);assert.equal(result.status,'FAILED_TO_ARCHIVE');assert.ok(fs.existsSync(f));});
test('P8-22 case artifacts and index survive restart',()=>{const{root,store}=setup();const c=store.create(source()).case;store.writeArtifact(c.case_id,'normalized/initial-bill.json',{model_version:'1'});const restarted=new CaseStore(root);assert.equal(restarted.findByHash('hash-a').case_id,c.case_id);assert.equal(require(path.join(restarted.directory(c.case_id),'normalized','initial-bill.json')).model_version,'1');});
test('P8-23 multiple queued cases cannot replace locked browser context',()=>{const{root,store}=setup();const a=store.create(source('a')).case,b=store.create(source('b')).case;const lock=new ActiveCaseLock(root,{pid:process.pid});lock.acquire(a.case_id);const svc=new CaseWorkflowService({store,lock,rateRepository:{},registrySnapshot:()=>({}),storageRoot:root});assert.throws(()=>svc.openCase(b.case_id),/ACTIVE_CASE_LOCKED/);assert.equal(svc.openCase(a.case_id).case_id,a.case_id);lock.release();});
test('P8-24 large inbox scan is sorted deterministic and defers hashing until stable',()=>{const{root}=setup();const s=new InboxScanner(root,{minAgeMs:0});for(let i=199;i>=0;i--)makePdf(s.initial,`${String(i).padStart(3,'0')}.pdf`, `%PDF-${i}`);const first=s.scan();assert.equal(first.length,200);assert.ok(first.every(x=>x.status==='WAITING_FOR_STABLE_FILE'));const second=s.scan();assert.ok(second.every(x=>x.status==='STABLE'));assert.deepEqual(second.map(x=>x.file_name),[...second.map(x=>x.file_name)].sort());});
