'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { ensureStorage } = require('../../src/core/storage');
const { CustomCodeRegistry } = require('../../src/services/custom-codes/custom-code-registry');
const { createReviewQueue } = require('../../src/services/custom-codes/review-queue');
const { parseBillDocument } = require('../../src/services/bill-ingestion/bill-parser');
const { loadRateSource, RateRepository, evaluateBill } = require('../../src/services/cghs');
const { adaptEnhancementPlan } = require('../../src/adapters/legacy-portal/plan-adapter');

const ratesPath = path.join(__dirname, '..', 'fixtures', 'rates', 'authoritative-test-rates.json');
const snapshotPath = path.join(__dirname, '..', '..', 'src', 'services', 'cghs', 'data', 'hfos-reference-rates.json');
function sha(file) { return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'); }
function setup() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'vnext-custom-')); ensureStorage(root);
  let id = 0; const options = { clock: () => new Date('2026-09-26T10:00:00.000Z'), idFactory: () => `event-${++id}` };
  return { root, options, registry: new CustomCodeRegistry(root, options) };
}
function input(code = 'LC001', extra = {}) { return { code, description: 'Local procedure', quantity_behavior: 'FIXED', fixed_quantity: 2, reason: 'Approved local slot', source: 'Hospital circular 7', operator: 'OP-1', ...extra }; }
function referenceRepo() { return new RateRepository(loadRateSource(ratesPath)); }
function repo(registry) { return new RateRepository(loadRateSource(ratesPath), registry.activeRateEntries(), { customRegistrySnapshot: registry.snapshot() }); }
function bill(code = 'LC001') { return parseBillDocument({ source: { file_name: 'custom.pdf', sha256: 'synthetic' }, pages: [{ page_number: 1, lines: ['Investigations', `Service: Local | Code: ${code} | Qty: 9`], raw_text: `Investigations\nService: Local | Code: ${code} | Qty: 9` }] }); }

// Twenty deterministic Phase 6 acceptance/regression cases.
test('P6-01 creates a valid custom code without fabricating a rate', () => { const { registry } = setup(); const r = registry.create(input()); assert.equal(r.code, 'LC001'); assert.equal(r.rate, null); assert.equal(r.scope, 'GLOBAL'); });
test('P6-02 rejects malformed custom codes and preserves entered value only in valid records', () => { const { registry } = setup(); assert.throws(() => registry.create(input('bad code')), /format is invalid/); assert.equal(registry.list().length, 0); });
test('P6-03 detects duplicate custom records including inactive records', () => { const { registry } = setup(); registry.create(input()); registry.setActive('LC001', false, { reason: 'Retired', source: 'Local notice', operator: 'OP-1' }); assert.throws(() => registry.create(input('lc001')), /Duplicate custom code/); });
test('P6-04 rejects reference/custom collision without explicit override', () => { const { registry } = setup(); assert.throws(() => registry.create(input('B126'), { referenceLookup: (code) => referenceRepo().lookup(code) }), /requires override_authoritative/); });
test('P6-05 permits and labels an explicit reference override without modifying reference', () => { const { registry } = setup(); const r = registry.create(input('B126', { override_authoritative: true }), { referenceLookup: (code) => referenceRepo().lookup(code) }); assert.equal(r.override_authoritative, true); assert.equal(repo(registry).lookup('B126').status, 'CUSTOM/LOCAL'); assert.equal(referenceRepo().lookup('B126').status, 'VALID'); });
test('P6-06 unknown code resolves UNKNOWN before explicit creation', () => { const { registry } = setup(); assert.equal(repo(registry).lookup('LC001').status, 'UNKNOWN'); });
test('P6-07 unknown code resolves CUSTOM/LOCAL and plan CUSTOM_VALID after creation', () => { const { registry } = setup(); registry.create(input()); const plan = evaluateBill(bill(), repo(registry)); assert.equal(plan.entries[0].status, 'CUSTOM_VALID'); assert.equal(plan.entries[0].quantity, 2); });
test('P6-08 deactivated custom code no longer resolves or executes', () => { const { registry } = setup(); registry.create(input()); registry.setActive('LC001', false, { reason: 'Do not use', source: 'Notice', operator: 'OP-1' }); assert.equal(repo(registry).lookup('LC001').status, 'UNKNOWN'); assert.equal(evaluateBill(bill(), repo(registry)).entries[0].status, 'UNKNOWN_CODE'); });
test('P6-09 missing-code advisory remains REVIEW_REQUIRED', () => { const parsed = parseBillDocument({ source: { file_name: 'missing.pdf' }, pages: [{ page_number: 1, lines: ['Investigations', 'Service: Missing | Qty: 1'], raw_text: 'Investigations\nService: Missing | Qty: 1' }] }); const plan = evaluateBill(parsed, referenceRepo()); assert.equal(plan.rejected_candidates[0].status, 'REVIEW_REQUIRED'); assert.equal(createReviewQueue(plan)[0].reason, 'POSSIBLY_MISSING_CODE'); });
test('P6-10 missing-code advisory never auto-creates a code', () => { const { registry } = setup(); registry.recordReview({ reason: 'Needs coding review', source: 'Bill page 1', operator: 'OP-1', review_record: { reason: 'POSSIBLY_MISSING_CODE' } }); assert.equal(registry.list().length, 0); });
test('P6-11 bill-specific review decision does not create global custom code', () => { const { registry } = setup(); const e = registry.recordReview({ action: 'REVIEWED', code: 'LC001', reason: 'Dismissed for this bill', source: 'Bill 1', operator: 'OP-1', bill_context: { bill: '1' } }); assert.equal(e.scope, 'BILL_SPECIFIC'); assert.equal(registry.get('LC001'), null); });
test('P6-12 explicit Add Custom Code creates a global record', () => { const { registry } = setup(); assert.equal(registry.create(input()).scope, 'GLOBAL'); assert.equal(registry.list().length, 1); });
test('P6-13 registry persists across application restart simulation', () => { const { registry, root, options } = setup(); registry.create(input()); const restarted = new CustomCodeRegistry(root, options); assert.equal(restarted.get('LC001').description, 'Local procedure'); assert.equal(restarted.snapshot().revision, 1); });
test('P6-14 plan captures registry revision hash and relevant record fingerprint', () => { const { registry } = setup(); registry.create(input()); const plan = evaluateBill(bill(), repo(registry)); assert.equal(plan.custom_registry.revision, 1); assert.equal(plan.custom_registry.hash.length, 64); assert.equal(typeof plan.custom_registry.relevant_record_hashes.LC001, 'string'); });
test('P6-15 relevant registry change marks an existing plan stale', () => { const { registry } = setup(); registry.create(input()); const plan = evaluateBill(bill(), repo(registry)); registry.update('LC001', { description: 'Changed', reason: 'Revision', source: 'Notice 2', operator: 'OP-2', quantity_behavior: 'FIXED', fixed_quantity: 3 }); assert.throws(() => adaptEnhancementPlan(plan, { registrySnapshot: registry.snapshot() }), /PLAN_STALE/); });
test('P6-16 stale plan cannot silently cross the Phase 4 boundary', () => { const { registry } = setup(); const plan = evaluateBill(bill(), repo(registry)); registry.create(input()); let error; try { adaptEnhancementPlan(plan, { registrySnapshot: registry.snapshot() }); } catch (caught) { error = caught; } assert.equal(error.code, 'PLAN_STALE'); assert.deepEqual(error.stale_codes, ['LC001']); });
test('P6-17 validated fixed-quantity custom code reaches Phase 4 with registry audit identity', () => { const { registry } = setup(); registry.create(input()); const plan = evaluateBill(bill(), repo(registry)); const request = adaptEnhancementPlan(plan, { registrySnapshot: registry.snapshot(), runId: 'custom-run' }); assert.equal(request.actions[0].code, 'LC001'); assert.equal(request.actions[0].quantity, 2); assert.equal(request.actions[0].plan_status, 'CUSTOM_VALID'); assert.equal(request.custom_registry.revision, 1); });
test('P6-18 manual custom, unknown, and unresolved compound records remain blocked/reviewable', () => { const { registry } = setup(); registry.create(input('LC001', { quantity_behavior: 'MANUAL', fixed_quantity: null })); const parsed = parseBillDocument({ source: { file_name: 'mixed.pdf' }, pages: [{ page_number: 1, lines: ['Investigations', 'Service: Manual | Code: LC001 | Qty: 1', 'Service: Unknown | Code: ZZ999 | Qty: 1', 'Service: Compound | Code: B068+L | Qty: 1'], raw_text: 'Investigations' }] }); const plan = evaluateBill(parsed, repo(registry)); const request = adaptEnhancementPlan(plan, { registrySnapshot: registry.snapshot() }); assert.equal(request.actions.length, 0); assert.equal(request.blocked.length, 3); });
test('P6-19 custom operations leave the 1,998-record reference snapshot byte-identical', () => { const before = sha(snapshotPath); const { registry } = setup(); registry.create(input()); registry.update('LC001', { description: 'Updated', reason: 'Correction', source: 'Notice', operator: 'OP-1', quantity_behavior: 'FIXED', fixed_quantity: 4 }); assert.equal(sha(snapshotPath), before); assert.equal(before, 'b606c25a035d0b49f433741655c64ca0e019e9fc701d3b534968361804d1a5ba'); });
test('P6-20 lifecycle and review audit records contain actor reason source old/new and revision', () => { const { registry } = setup(); registry.create(input()); registry.recordPlanUsage(evaluateBill(bill(), repo(registry))); registry.setActive('LC001', false, { reason: 'Retired', source: 'Notice', operator: 'OP-2' }); registry.recordReview({ action: 'REVIEWED', code: 'LC001', reason: 'Checked', source: 'Bill', operator: 'OP-3' }); const audit = registry.audit('LC001'); assert.deepEqual(audit.map((x) => x.action), ['CREATED', 'USED_IN_PLAN', 'DEACTIVATED', 'REVIEWED']); assert.equal(audit[0].new_value.code, 'LC001'); assert.equal(audit[2].old_value.active, true); assert.equal(audit[3].operator, 'OP-3'); });
