'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const finalFixture = require('../fixtures/bills/final-bill-sections.json');
const { ensureStorage } = require('../../src/core/storage');
const { parseBillDocument } = require('../../src/services/bill-ingestion/bill-parser');
const { loadRateSource, RateRepository, evaluateBill } = require('../../src/services/cghs');
const { createCompletedBill, extractFinalSections, reconcileFinalBill, resolveFinalBillMatch, saveCompletedBill } = require('../../src/services/final-bill');

const rates = new RateRepository(loadRateSource(path.join(__dirname, '..', 'fixtures', 'rates', 'authoritative-test-rates.json')));
function structured(lines, source = {}) { return { source: { file_name: 'bill.pdf', sha256: 'hash', ...source }, pages: [{ page_number: 1, lines, raw_text: lines.join('\n') }] }; }
function initialBill(extra = {}) { return parseBillDocument(structured(['Bill No: SYN-500', 'UHID: UH-500', 'IP No: IP-500', 'Investigations', 'Service: Test | Code: B126 | Qty: 1'], { file_name: 'initial.pdf', sha256: 'initial-hash', ...extra })); }
function finalBill() { return parseBillDocument(finalFixture); }
function completed(overrides = {}) {
  const initial = overrides.initialBill || initialBill(); const final = overrides.finalBill || finalBill();
  return createCompletedBill({ initialBill: initial, finalBill: final, enhancementPlan: evaluateBill(initial, rates), rateRepository: rates, runId: overrides.runId || 'final-run-1', timestamp: overrides.timestamp || '2026-09-26T12:00:00.000Z', executionAudit: overrides.executionAudit || null });
}

// Twenty-two deterministic Phase 7 cases; no real patient data or portal access is used.
test('P7-01 extracts and aggregates IP Pharmacy', () => { const x = extractFinalSections(finalBill(), rates); assert.equal(x.pharmacy_records.find((r) => r.section === 'IP_PHARMACY').quantity, 5); });
test('P7-02 extracts OP Pharmacy separately', () => { const x = extractFinalSections(finalBill(), rates); assert.equal(x.pharmacy_records.find((r) => r.section === 'OP_PHARMACY').quantity, 1); });
test('P7-03 extracts OT Pharmacy separately', () => { const x = extractFinalSections(finalBill(), rates); assert.equal(x.pharmacy_records.find((r) => r.section === 'OT_PHARMACY').quantity, 2); });
test('P7-04 extracts OT Consumables', () => { const x = extractFinalSections(finalBill(), rates); assert.equal(x.consumable_records.find((r) => r.section === 'OT_CONSUMABLES').quantity, 4); });
test('P7-05 extracts explicitly headed Ward Consumables', () => { const x = extractFinalSections(finalBill(), rates); assert.equal(x.consumable_records.find((r) => r.section === 'WARD_CONSUMABLES').quantity, 5); });
test('P7-06 extracts explicitly headed Cathlab Consumables', () => { const x = extractFinalSections(finalBill(), rates); assert.equal(x.consumable_records.find((r) => r.section === 'CATHLAB_CONSUMABLES').quantity, 6); });
test('P7-07 preserves multiple recognized sections across pages', () => { const x = extractFinalSections(finalBill(), rates); assert.deepEqual(x.extracted_sections.filter((s) => s.context === 'PRIMARY_BILL').map((s) => s.section), finalFixture.expected.sections); });
test('P7-08 excludes Patient Payable IP Pharmacy', () => { const x = extractFinalSections(finalBill(), rates); assert.equal(x.excluded_records.length, 1); assert.equal(x.excluded_records[0].quantity, 99); assert.equal(x.excluded_records[0].status, 'EXCLUDED_BY_SECTION'); });
test('P7-09 duplicate product aggregates only within the same section', () => { const x = extractFinalSections(finalBill(), rates); const ip = x.pharmacy_records.find((r) => r.section === 'IP_PHARMACY'); assert.equal(ip.occurrence_count, 2); assert.equal(ip.source_evidence.length, 2); });
test('P7-10 same code remains separate across IP and OP Pharmacy', () => { const x = extractFinalSections(finalBill(), rates); const b126 = x.pharmacy_records.filter((r) => r.normalized_code === 'B126'); assert.deepEqual(b126.map((r) => [r.section, r.quantity]), [['IP_PHARMACY', 5], ['OP_PHARMACY', 1]]); });
test('P7-11 unknown explicitly coded final item remains review-required', () => { const bill = parseBillDocument(structured(['Bill No: SYN-500', 'IP Pharmacy', 'Service: Unknown | Code: ZZ999 | Qty: 1'], { sha256: 'unknown-final' })); const x = extractFinalSections(bill, rates); assert.equal(x.pharmacy_records[0].code_classification, 'UNKNOWN'); assert.equal(x.pharmacy_records[0].status, 'REVIEW_REQUIRED'); });
test('P7-12 compound final item remains unresolved and is never expanded', () => { const bill = parseBillDocument(structured(['Bill No: SYN-500', 'OT Pharmacy', 'Service: Pack | Code: B068+L / B075+L | Qty: 1'], { sha256: 'compound-final' })); const x = extractFinalSections(bill, rates); assert.equal(x.pharmacy_records[0].code_classification, 'UNRESOLVED_COMPOUND'); assert.equal(x.pharmacy_records[0].reason, 'COMPOUND_SEMANTICS_NOT_INFERRED'); });
test('P7-13 missing pharmacy/consumable sections require review', () => { const bill = parseBillDocument(structured(['Bill No: SYN-500', 'Investigations', 'Service: Test | Code: B126 | Qty: 1'], { sha256: 'no-final-sections' })); assert.equal(extractFinalSections(bill, rates).review_required_records[0].reason, 'NO_FINAL_PHARMACY_OR_CONSUMABLE_SECTIONS'); });
test('P7-14 ambiguous pharmacy/consumable heading requires review instead of guessing', () => { const bill = parseBillDocument(structured(['Bill No: SYN-500', 'Pharmacy / Consumables', 'Item: Maybe | Qty: 1'], { sha256: 'ambiguous-final' })); const reviews = extractFinalSections(bill, rates).review_required_records; assert.ok(reviews.some((r) => r.reason === 'AMBIGUOUS_FINAL_SECTION_HEADING')); });
test('P7-15 matching final bill links deterministically and preserves historical plan reference', () => { const result = completed({ executionAudit: { run_id: 'portal-1', status: 'EXECUTED', completed_at: '2026-09-26T11:00:00Z' } }); assert.equal(result.reconciliation.status, 'MATCHED'); assert.equal(result.status, 'PARSED'); assert.equal(result.enhancement_plan_reference.bill.source_file, 'initial.pdf'); assert.equal(result.enhancement_execution_reference.run_id, 'portal-1'); });
test('P7-16 conflicting identifier stops automatic reconciliation', () => { const mismatch = parseBillDocument(structured(['Bill No: OTHER-1', 'UHID: UH-500', 'IP Pharmacy', 'Service: A | Code: B126 | Qty: 1'], { sha256: 'mismatch-final' })); const result = completed({ finalBill: mismatch }); assert.equal(result.status, 'MATCH_REQUIRED'); assert.ok(result.reconciliation.reasons.includes('BILL_NUMBER_MISMATCH')); });
test('P7-17 missing shared identifying metadata requires manual match', () => { const noIds = parseBillDocument(structured(['IP Pharmacy', 'Service: A | Code: B126 | Qty: 1'], { sha256: 'missing-id-final' })); assert.equal(reconcileFinalBill(initialBill(), noIds).decision, 'INSUFFICIENT_IDENTIFIERS'); const pending = completed({ finalBill: noIds }); const resolved = resolveFinalBillMatch(pending, { operator: 'OP-1', reason: 'Verified source document manually', timestamp: '2026-09-26T12:30:00Z' }); assert.equal(resolved.reconciliation.decision, 'MANUAL_EXPLICIT_MATCH'); });
test('P7-18 duplicate final PDF hash is detected without creating another package', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'final-store-')); ensureStorage(root); const first = saveCompletedBill(root, completed(), { timestamp: '2026-09-26T12:01:00Z' }); const duplicate = saveCompletedBill(root, completed({ runId: 'final-run-2' })); assert.equal(first.status, 'COMPLETED'); assert.equal(duplicate.status, 'DUPLICATE_FINAL_PDF'); assert.equal(duplicate.existing.length, 1); });
test('P7-19 successful persistence writes normalized record and extraction audit outside executable', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'final-store-')); ensureStorage(root); const saved = saveCompletedBill(root, completed(), { timestamp: '2026-09-26T12:01:00Z' }); assert.equal(saved.status, 'COMPLETED'); assert.ok(saved.package_path.startsWith(path.join(root, 'Bills'))); assert.ok(fs.existsSync(path.join(saved.package_path, 'normalized', 'completed-bill.json'))); assert.ok(fs.existsSync(path.join(saved.package_path, 'audit', 'extraction-audit.json'))); assert.equal(JSON.parse(fs.readFileSync(path.join(saved.package_path, 'normalized', 'completed-bill.json'))).status, 'COMPLETED'); });
test('P7-20 storage failure is explicit and never reports completed', () => { const result = saveCompletedBill('relative-storage', completed()); assert.equal(result.status, 'SAVE_FAILED'); assert.match(result.reason, /absolute/); });
test('P7-21 explicit reprocessing creates a controlled new version without overwrite', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'final-store-')); ensureStorage(root); const first = saveCompletedBill(root, completed()); const second = saveCompletedBill(root, completed({ runId: 'final-run-2' }), { allowReprocess: true }); assert.equal(first.version, 1); assert.equal(second.version, 2); assert.notEqual(first.package_path, second.package_path); assert.ok(fs.existsSync(first.package_path)); });
test('P7-22 large final bill extracts all rows with section-aware aggregation', () => { const lines = ['Bill No: SYN-500', 'IP Pharmacy', ...Array.from({ length: 1000 }, (_, i) => `Service: Medicine ${i % 10} | Code: B126 | Qty: 1`)]; const bill = parseBillDocument(structured(lines, { sha256: 'large-final' })); const x = extractFinalSections(bill, rates); assert.equal(x.pharmacy_records.length, 1); assert.equal(x.pharmacy_records[0].quantity, 1000); assert.equal(x.pharmacy_records[0].source_evidence.length, 1000); });
