'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {InboxScanner}=require('../../src/services/cases/inbox-scanner');const {InboxWatcher,STATES}=require('../../src/services/cases/inbox-watcher');const {loadConfig}=require('../../src/core/config');
function timer(){return{setInterval:()=>1,clearInterval:()=>{}};}function setup(options={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'watch-'));let now=Date.now()+10000;const scanner=new InboxScanner(root,{clock:()=>now,minAgeMs:0});const events=[],calls=[];const watcher=new InboxWatcher({scanner,clock:()=>new Date(now),timerApi:timer(),intervalMs:5000,maxQueue:options.maxQueue||100,concurrency:options.concurrency||1,audit:e=>events.push(e),processCandidate:options.process|| (async(kind,file)=>{calls.push({kind,file});return{outcome:'NEW_SOURCE',case:{case_id:file.sha256}};})});return{root,scanner,watcher,events,calls,tick:()=>{now++}};}
function pdf(dir,name,body='%PDF-1.4'){const f=path.join(dir,name);fs.writeFileSync(f,body);return f;}async function stable(s,w,kind='initial'){s.scan(kind);await w.scanNow();}

test('P11-01 automatic mode disabled by default',()=>assert.equal(loadConfig({appDir:path.resolve(__dirname,'../..')}).automaticInboxWatch.enabled,false));
test('P11-02 watcher starts explicitly',()=>{const{x:_,watcher}=setup();assert.equal(watcher.state,STATES.STOPPED);assert.equal(watcher.start().state,STATES.RUNNING);});
test('P11-03 watcher stops cleanly',async()=>{const{watcher}=setup();watcher.start();assert.equal((await watcher.stop()).state,STATES.STOPPED);});
test('P11-04 pause prevents scans',async()=>{const{watcher,scanner}=setup();pdf(scanner.initial,'a.pdf');watcher.start();watcher.pause();await watcher.scanNow();assert.equal(watcher.status().last_scan,null);});
test('P11-05 resume restores running',()=>{const{watcher}=setup();watcher.start();watcher.pause();assert.equal(watcher.resume().state,STATES.RUNNING);});
test('P11-06 stable initial uses initial workflow',async()=>{const{watcher,scanner,calls}=setup();pdf(scanner.initial,'a.pdf');watcher.start();await stable(scanner,watcher);assert.equal(calls[0].kind,'initial');});
test('P11-07 stable final uses final workflow',async()=>{const{watcher,scanner,calls}=setup();pdf(scanner.final,'a.pdf');watcher.start();await stable(scanner,watcher,'final');assert.equal(calls[0].kind,'final');});
test('P11-08 unstable waits and remains discoverable',async()=>{const{watcher,scanner,calls}=setup();pdf(scanner.initial,'a.pdf');watcher.start();await watcher.scanNow();assert.equal(calls.length,0);assert.equal(watcher.status().stats.waiting_for_stability,1);await watcher.scanNow();assert.equal(calls.length,1);});
test('P11-09 temporary/non-PDF/hidden ignored',async()=>{const{watcher,scanner,calls}=setup();for(const n of ['.a.pdf','a.tmp','a.part','a.crdownload','a.txt'])pdf(scanner.initial,n);watcher.start();await watcher.scanNow();assert.equal(calls.length,0);});
test('P11-10 deterministic initial/final ordering',async()=>{const{watcher,scanner,calls}=setup();pdf(scanner.final,'z.pdf');pdf(scanner.initial,'b.pdf','%PDF-b');pdf(scanner.initial,'a.pdf','%PDF-a');scanner.scan();scanner.scan('final');watcher.start();await watcher.scanNow();assert.deepEqual(calls.map(x=>`${x.kind}/${x.file.file_name}`),['final/z.pdf','initial/a.pdf','initial/b.pdf']);});
test('P11-11 exact duplicates are audited',async()=>{const s=setup({process:async()=>({outcome:'EXACT_DUPLICATE',case:{case_id:'c'}})});pdf(s.scanner.initial,'a.pdf');s.scanner.scan();s.watcher.start();await s.watcher.scanNow();assert.equal(s.watcher.status().stats.duplicates,1);assert.ok(s.events.some(e=>e.event==='DUPLICATE_DETECTED'));});
test('P11-12 repeated cycles depend on authoritative processor idempotency',async()=>{let seen=false;const s=setup({process:async()=>seen?{outcome:'EXACT_DUPLICATE'}:(seen=true,{outcome:'NEW_SOURCE',case:{case_id:'c'}})});pdf(s.scanner.initial,'a.pdf');s.scanner.scan();s.watcher.start();await s.watcher.scanNow();await s.watcher.scanNow();assert.equal(s.watcher.status().stats.new_cases,1);assert.equal(s.watcher.status().stats.duplicates,1);});
test('P11-13 queue full leaves candidate in inbox',async()=>{const s=setup({maxQueue:1});pdf(s.scanner.initial,'a.pdf','%PDF-a');pdf(s.scanner.initial,'b.pdf','%PDF-b');s.scanner.scan();s.scanner.scan('final');s.watcher.start();await s.watcher.scanNow();assert.ok(s.events.some(e=>e.event==='QUEUE_FULL'));assert.ok(fs.existsSync(path.join(s.scanner.initial,'b.pdf')));});
test('P11-14 one registration failure does not kill watcher',async()=>{let n=0;const s=setup({process:async()=>{if(!n++)throw Error('bad');return{outcome:'NEW_SOURCE',case:{case_id:'ok'}};}});pdf(s.scanner.initial,'a.pdf','%PDF-a');pdf(s.scanner.initial,'b.pdf','%PDF-b');s.scanner.scan();s.scanner.scan('final');s.watcher.start();await s.watcher.scanNow();assert.equal(s.watcher.state,STATES.RUNNING);assert.equal(s.watcher.status().stats.registration_errors,1);assert.equal(s.watcher.status().stats.new_cases,1);});
test('P11-15 scanner infrastructure failure enters ERROR',async()=>{const s=setup();s.watcher.scanner.scan=()=>{throw Error('disk')};s.watcher.start();await s.watcher.scanNow();assert.equal(s.watcher.state,STATES.ERROR);assert.ok(s.events.some(e=>e.event==='WATCHER_ERROR'));});
test('P11-16 archive failure explicit',async()=>{const s=setup({process:async()=>({outcome:'FAILED_TO_ARCHIVE',reason:'denied'})});pdf(s.scanner.initial,'a.pdf');s.scanner.scan();s.watcher.start();await s.watcher.scanNow();assert.ok(s.events.some(e=>e.event==='ARCHIVE_FAILED'));});
test('P11-17 watcher lifecycle and scan audit emitted',async()=>{const s=setup();s.watcher.start();await s.watcher.scanNow();s.watcher.pause();s.watcher.resume();await s.watcher.stop();for(const e of ['WATCHER_STARTED','SCAN_STARTED','SCAN_COMPLETED','WATCHER_PAUSED','WATCHER_RESUMED','WATCHER_STOPPED'])assert.ok(s.events.some(x=>x.event===e));});
test('P11-18 never receives portal lock/Selenium/CDP/discharge dependencies',()=>{const s=setup();assert.deepEqual(Object.keys(s.watcher).filter(k=>/^(selenium|chrome|cdp|lock|discharge|portal)/i.test(k)),[]);});
test('P11-19 status exposes bounded operational metrics',()=>{const{watcher}=setup({maxQueue:7,concurrency:2});const v=watcher.status();assert.equal(v.max_queue_size,7);assert.equal(v.concurrency,2);assert.equal(v.interval_ms,5000);});
test('P11-20 100-file deterministic bounded intake',async()=>{const s=setup({maxQueue:25});for(let i=99;i>=0;i--)pdf(s.scanner.initial,`${String(i).padStart(3,'0')}.pdf`,`%PDF-${i}`);s.scanner.scan();s.watcher.start();await s.watcher.scanNow();assert.equal(s.calls.length,25);assert.equal(s.events.filter(e=>e.event==='QUEUE_FULL').length,75);});
test('P11-21 500-file mixed inbox remains bounded and filters invalid files',async()=>{const s=setup({maxQueue:50});for(let i=0;i<250;i++){pdf(i%2?s.scanner.final:s.scanner.initial,`${String(i).padStart(3,'0')}.pdf`,`%PDF-${i}`);pdf(s.scanner.initial,`${i}.part`);}s.scanner.scan();s.scanner.scan('final');s.watcher.start();await s.watcher.scanNow();assert.equal(s.calls.length,50);assert.equal(s.events.filter(e=>e.event==='QUEUE_FULL').length,200);});
test('P11-22 stop prevents later scheduled scan',async()=>{const s=setup();s.watcher.start();await s.watcher.stop();await s.watcher.scanNow();assert.equal(s.watcher.lastScan,null);});
test('P11-23 manual and automatic scanner share same instance',()=>{const s=setup();assert.equal(s.watcher.scanner,s.scanner);});
test('P11-24 defaults are conservative and bounded',()=>{const c=loadConfig({appDir:path.resolve(__dirname,'../..')}).automaticInboxWatch;assert.deepEqual(c,{enabled:false,pollingIntervalMs:30000,stabilityWindowMs:1000,minimumFileAgeMs:1000,maximumQueueSize:100,backgroundConcurrency:1});});
