'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {parseBillDocument}=require('../../src/services/bill-ingestion/bill-parser');const {loadRateSource,RateRepository,evaluateBill}=require('../../src/services/cghs');const {validateBill,summarizeValidation}=require('../../src/services/validation/bill-validator');const {classifyDiscrepancy,loadValidation,saveValidation}=require('../../src/services/validation/validation-store');const {createReviewQueue}=require('../../src/services/custom-codes/review-queue');const {extractFinalSections}=require('../../src/services/final-bill');const {CaseStore}=require('../../src/services/cases/case-store');const {ensureStorage}=require('../../src/core/storage');
const ratesSource=loadRateSource(path.join(__dirname,'..','fixtures','rates','authoritative-test-rates.json'));function repo(custom=[]){return new RateRepository(ratesSource,custom);}
function input(lines,hash='validation-hash',pages=null){return{source:{file_name:'validation.pdf',sha256:hash},pages:pages||[{page_number:1,lines,raw_text:lines.join('\n')}]};}function directBill(hash='validation-hash'){return parseBillDocument(input(['Bill No: V-1','Investigations','Service: Test | Code: B126 | Qty: 2'],hash));}
function expected(hash='validation-hash',codes=[{code:'B126',section:'INVESTIGATIONS',kind:'DIRECT',quantity:2,status:'SOURCE_VERIFIED',evidence:{page:1,raw_text:'Service: Test | Code: B126 | Qty: 2'}}],extra={}){return{fixture_id:`fixture-${hash}`,source_sha256:hash,metadata:{privacy_approval_status:'SYNTHETIC'},expected:{codes,sections:[{section:'INVESTIGATIONS',context:'PRIMARY_BILL',evidence:{page:1,raw_text:'Investigations'}}],excluded:[],format_variations:[],...extra}};}
function validate(fixture=expected(),bill=directBill(),plan=evaluateBill(bill,repo()),extra={}){return validateBill({fixture,bill,plan,caseId:extra.caseId||'case-1',runId:extra.runId||'run-1',finalExtraction:extra.finalExtraction});}
function derivedBill(oxygen=null){const lines=['Bill No: D-1'];if(oxygen)lines.push('Hospital Services',`Service: ${oxygen} | Code: CC002 | Qty: 1`);else lines.push('Bed Details','01/09/2026 02/09/2026 1 days ICU-1 ICU','02/09/2026 03/09/2026 1 days W-1 General Ward');return parseBillDocument(input(lines,'derived-hash'));}
function derivedFixture(codes){return{fixture_id:'derived',source_sha256:'derived-hash',expected:{codes,sections:[],excluded:[],format_variations:[]}};}

test('P9-01 perfect reviewed baseline produces PASS and human summary',()=>{const r=validate();assert.equal(r.status,'PASS');assert.equal(r.matches.length,1);assert.match(summarizeValidation(r),/PASS/);});
test('P9-02 actual candidate absent from baseline is EXTRA_CODE',()=>{const b=parseBillDocument(input(['Investigations','Service: A | Code: B126 | Qty: 1','Service: B | Code: B075 | Qty: 1']));const r=validate(expected('validation-hash',[{code:'B126',section:'INVESTIGATIONS',kind:'DIRECT',quantity:1,status:'SOURCE_VERIFIED',evidence:{page:1}}]),b,evaluateBill(b,repo()));assert.ok(r.discrepancies.some(x=>x.type==='EXTRA_CODE'&&x.code==='B075'));});
test('P9-03 evidence-backed absent expected code is POSSIBLY_MISSING_CODE',()=>{const f=expected('validation-hash',[{code:'B075',section:'INVESTIGATIONS',kind:'DIRECT',quantity:1,status:'SOURCE_VERIFIED',evidence:{page:1,raw_text:'reviewed coded row'}}]);assert.equal(validate(f).discrepancies[0].type,'POSSIBLY_MISSING_CODE');});
test('P9-04 insufficient evidence never reports a guessed missing code',()=>{const f=expected('validation-hash',[{code:'B075',section:'INVESTIGATIONS',kind:'DIRECT',quantity:1,status:'SOURCE_VERIFIED'}]);const d=validate(f).discrepancies[0];assert.equal(d.type,'REVIEW_REQUIRED');assert.equal(d.code,null);});
test('P9-05 quantity is validated independently from code presence',()=>{const f=expected('validation-hash',[{code:'B126',section:'INVESTIGATIONS',kind:'DIRECT',quantity:9,status:'SOURCE_VERIFIED',evidence:{page:1}}]);assert.equal(validate(f).discrepancies[0].type,'QUANTITY_MISMATCH');});
test('P9-06 missing expected section is SECTION_MISMATCH',()=>{const f=expected('validation-hash',expected().expected.codes,{sections:[{section:'OT_PHARMACY',context:'PRIMARY_BILL',evidence:{page:2}}]});assert.ok(validate(f).discrepancies.some(x=>x.type==='SECTION_MISMATCH'));});
test('P9-07 Patient Payable provenance leaking into plan is EXCLUSION_MISMATCH',()=>{const b=parseBillDocument(input(['Patient Payable','IP Pharmacy','Service: Excluded | Code: B126 | Qty: 3','Patient Payable Total: 3'],'pay-hash'));const p=evaluateBill(b,repo());const excluded=b.excluded_sections.flatMap(s=>s.items)[0];p.entries.push({code:'B126',quantity:3,status:'SOURCE_VERIFIED',source:'DIRECT_BILL_CODE',provenance:[{occurrence_id:excluded.id,source_section:'IP_PHARMACY'}]});const f={fixture_id:'pay',source_sha256:'pay-hash',expected:{codes:[],sections:[],excluded:[{code:'B126',section:'IP_PHARMACY',evidence:{page:1}}]}};assert.ok(validateBill({fixture:f,bill:b,plan:p}).discrepancies.some(x=>x.type==='EXCLUSION_MISMATCH'&&/LEAKED/.test(x.reason)));});
test('P9-08 CN002 derived mismatch is rule-level',()=>{const b=derivedBill(),p=evaluateBill(b,repo());const f=derivedFixture([{code:'CN002',section:null,kind:'DERIVED',quantity:99,status:'RULE_VERIFIED',evidence:{rule_id:'CN002_ROOM_BED'}}]);const d=validateBill({fixture:f,bill:b,plan:p}).discrepancies.find(x=>x.code==='CN002');assert.equal(d.type,'DERIVED_QUANTITY_MISMATCH');});
test('P9-09 CC001 derived mismatch remains separate',()=>{const b=derivedBill(),p=evaluateBill(b,repo());const f=derivedFixture([{code:'CC001',section:null,kind:'DERIVED',quantity:2,status:'RULE_VERIFIED',evidence:{rule_id:'CC001_ICU_ROOM_RENT'}}]);assert.equal(validateBill({fixture:f,bill:b,plan:p}).discrepancies.find(x=>x.code==='CC001').type,'DERIVED_QUANTITY_MISMATCH');});
test('P9-10 WC001 derived mismatch remains separate',()=>{const b=derivedBill(),p=evaluateBill(b,repo());const f=derivedFixture([{code:'WC001',section:null,kind:'DERIVED',quantity:2,status:'RULE_VERIFIED',evidence:{rule_id:'WC001_WARD_ROOM_RENT'}}]);assert.equal(validateBill({fixture:f,bill:b,plan:p}).discrepancies.find(x=>x.code==='WC001').type,'DERIVED_QUANTITY_MISMATCH');});
test('P9-11 CC002 quantity mismatch reports derived discrepancy',()=>{const b=derivedBill('HALF DAY oxygen'),p=evaluateBill(b,repo());const f=derivedFixture([{code:'CC002',section:null,kind:'DERIVED',quantity:24,status:'RULE_VERIFIED',evidence:{rule_id:'CC002_OXYGEN_ROW'}}]);assert.equal(validateBill({fixture:f,bill:b,plan:p}).discrepancies.find(x=>x.code==='CC002').type,'DERIVED_QUANTITY_MISMATCH');});
test('P9-12 unknown code discrepancy is explicit',()=>{const b=parseBillDocument(input(['Investigations','Service: U | Code: ZZ999 | Qty: 1']));const p=evaluateBill(b,repo());const r=validate(expected('validation-hash',[]),b,p);assert.ok(r.discrepancies.some(x=>x.type==='UNKNOWN_CODE'&&x.code==='ZZ999'));});
test('P9-13 unresolved compound is a valid explicit discrepancy without mapping',()=>{const b=parseBillDocument(input(['Investigations','Service: C | Code: B068+L | Qty: 1']));const p=evaluateBill(b,repo());const f=expected('validation-hash',[{code:'B068+L',section:'INVESTIGATIONS',kind:'DIRECT',quantity:1,status:'RULE_UNDEFINED',compound:true,evidence:{page:1}}]);const r=validate(f,b,p);assert.ok(r.matches.some(x=>x.code==='B068+L'));assert.ok(r.discrepancies.some(x=>x.type==='UNRESOLVED_COMPOUND'));});
test('P9-14 custom code remains CUSTOM_VALID rather than reference-valid',()=>{const custom={code:'LC001',description:'Local',rate:null,audit:{reason:'Approved',created_by:'OP',created_at:'2026-09-26T00:00:00Z',quantity_behavior:'FIXED',fixed_quantity:2}};const b=parseBillDocument(input(['Investigations','Service: L | Code: LC001 | Qty: 1']));const p=evaluateBill(b,repo([custom]));const f=expected('validation-hash',[{code:'LC001',section:'INVESTIGATIONS',kind:'DIRECT',quantity:2,status:'CUSTOM_VALID',evidence:{page:1}}]);assert.equal(validate(f,b,p).status,'PASS');});
test('P9-15 human FALSE_POSITIVE classification changes review only, not findings',()=>{const r=validate(expected('validation-hash',[]));const id=r.discrepancies[0].discrepancy_id;const next=classifyDiscrepancy(r,id,{classification:'FALSE_POSITIVE',operator:'OP',reason:'Reviewed',timestamp:'2026-09-26T00:00:00Z'});assert.equal(next.discrepancies[0].type,'EXTRA_CODE');assert.equal(next.discrepancies[0].review_status,'FALSE_POSITIVE');});
test('P9-16 EXPECTED_VARIATION classification is supported without auto-fix',()=>{const r=validate(expected('validation-hash',[]));const next=classifyDiscrepancy(r,r.discrepancies[0].discrepancy_id,{classification:'EXPECTED_VARIATION',operator:'OP',reason:'Reviewed format'});assert.equal(next.discrepancies[0].review_status,'EXPECTED_VARIATION');assert.throws(()=>classifyDiscrepancy(r,r.discrepancies[0].discrepancy_id,{classification:'AUTO_FIX',operator:'OP',reason:'no'}),/Unsupported/);});
test('P9-17 validator never mutates or silently updates expected baseline',()=>{const f=expected();const before=JSON.stringify(f);validate(f);assert.equal(JSON.stringify(f),before);});
test('P9-18 duplicate aggregation validates equivalent total rather than row ordering',()=>{const b=parseBillDocument(input(['Investigations','Service: A | Code: B126 | Qty: 1','Service: A | Code: B126 | Qty: 2']));const f=expected('validation-hash',[{code:'B126',section:'INVESTIGATIONS',kind:'DIRECT',quantity:3,status:'SOURCE_VERIFIED',evidence:{page:1}}]);assert.equal(validate(f,b,evaluateBill(b,repo())).status,'PASS');});
test('P9-19 multi-page continuation section validates once',()=>{const pages=[{page_number:1,lines:['Investigations','Service: A | Code: B126 | Qty: 1'],raw_text:'Investigations\nService: A | Code: B126 | Qty: 1'},{page_number:2,lines:['Service: A | Code: B126 | Qty: 1'],raw_text:'Service: A | Code: B126 | Qty: 1'}];const b=parseBillDocument(input([], 'multi-hash',pages));const f=expected('multi-hash',[{code:'B126',section:'INVESTIGATIONS',kind:'DIRECT',quantity:2,status:'SOURCE_VERIFIED',evidence:{page:1}}]);assert.equal(validate(f,b,evaluateBill(b,repo())).status,'PASS');});
test('P9-20 large synthetic bill validates in one normalized aggregate',()=>{const lines=['Investigations',...Array.from({length:1000},()=> 'Service: A | Code: B126 | Qty: 1')];const b=parseBillDocument(input(lines,'large-hash'));const f=expected('large-hash',[{code:'B126',section:'INVESTIGATIONS',kind:'DIRECT',quantity:1000,status:'SOURCE_VERIFIED',evidence:{page:1}}]);assert.equal(validate(f,b,evaluateBill(b,repo())).status,'PASS');});
test('P9-21 case/run identity does not leak between validation reports',()=>{const a=validate(expected(),directBill(),evaluateBill(directBill(),repo()),{caseId:'A',runId:'1'}),b=validate(expected(),directBill(),evaluateBill(directBill(),repo()),{caseId:'B',runId:'2'});assert.deepEqual([a.case_id,a.run_id,b.case_id,b.run_id],['A','1','B','2']);});
test('P9-22 source hash and parser/plan versions are recorded',()=>{const r=validate();assert.equal(r.source_sha256,'validation-hash');assert.equal(r.parser_model_version,'1.0.0');assert.equal(r.plan_version,'1.0.0');});
test('P9-23 validation result persists and reloads after restart',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'validation-store-'));ensureStorage(root);let id=0;const store=new CaseStore(root,{idFactory:()=>`id-${++id}`});const c=store.create({file_name:'x.pdf',sha256:'x'}).case;const report=validate(expected(),directBill(),evaluateBill(directBill(),repo()),{caseId:c.case_id,runId:'persisted'});saveValidation(store,c.case_id,report);const restarted=new CaseStore(root);assert.equal(loadValidation(restarted,c.case_id,'persisted').source_sha256,'validation-hash');});
test('P9-24 discrepancies extend the existing Phase 6 review queue',()=>{const b=directBill(),p=evaluateBill(b,repo()),r=validate(expected('validation-hash',[]),b,p);const queue=createReviewQueue(p,r.discrepancies);assert.ok(queue.some(x=>x.scope==='VALIDATION'&&x.status==='EXTRA_CODE'));});
test('P9-25 final-bill section validation does not turn enrichment into enhancement',()=>{const final=parseBillDocument(input(['IP Pharmacy','Service: Med | Code: B126 | Qty: 1'],'final-hash'));const extraction=extractFinalSections(final,repo());const initial=directBill('final-hash'),plan=evaluateBill(initial,repo());const f=expected('final-hash',expected('final-hash').expected.codes,{final_records:[{section:'IP_PHARMACY',code:'B126',evidence:{page:1}}]});const count=plan.entries.length;validateBill({fixture:f,bill:initial,plan,finalExtraction:extraction});assert.equal(plan.entries.length,count);});
test('P9-26 validation is compatible with persistent Phase 8 case lifecycle',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'validation-case-'));ensureStorage(root);const store=new CaseStore(root);const c=store.create({file_name:'x.pdf',sha256:'x'}).case;const report=validate(expected(),directBill(),evaluateBill(directBill(),repo()),{caseId:c.case_id,runId:'case-run'});saveValidation(store,c.case_id,report);assert.equal(store.load(c.case_id).workflow_status,'NEW');assert.ok(store.auditRecords(c.case_id).some(x=>x.event==='VALIDATION_RECORDED'));});
